### ISSUE TITLE
[BACK-END] Implementation of /api/to-do

### ISSUE THREAD

**Issue by matheuspor** [matheuspor/ToDo-List#1]
### Tasks by priority

- [ ] Implements mongoose and add a Task model to the todo-list collection. 
- [ ] Implements route, model, service and a controller layer.
- [ ] Implements GET /api/to-do.
- [ ] Implements POST /api/to-do.
- [ ] Implements DELETE /api/to-do.
- [ ] Implements PATCH /api/to-do.
- [ ] Implements PUT /api/to-do.
- [ ] Add unit tests.
- [ ] Add E2E tests.
